# Generated by Django 5.0.1 on 2024-01-08 16:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apiculteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cheptel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('apiculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheptels', to='TP.apiculteur')),
            ],
            options={
                'verbose_name': 'cheptel',
                'verbose_name_plural': 'cheptels',
            },
        ),
        migrations.CreateModel(
            name='Ruche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('en_attente', 'En attente'), ('detruite', 'Détruite')], max_length=20)),
                ('date_statut', models.DateField()),
                ('annee_reine', models.PositiveIntegerField()),
                ('type_abeille', models.CharField(choices=[('apis_mellifera', 'Apis mellifera (Abeille européenne)'), ('apis_cerana', 'Apis cerana (Abeille asiatique)'), ('apis_mellifera_mellifera', 'Apis Mellifera Mellifera (Abeille noire)'), ('apis_mellifera_ligustica', 'Apis Mellifera Ligustica (Abeille italienne)'), ('apis_mellifera_caucasica', 'Apis mellifera caucasica (Abeille caucasienne)'), ('apis_mellifera_carnica', 'Apis mellifera carnica (Abeille carolienne)'), ('abeille_buckfast', "L'abeille Buckfast"), ('abeille_charpentière_xylocope', "L'abeille charpentière xylocope"), ('autre', 'Autre')], max_length=29)),
                ('contamination', models.BooleanField()),
                ('cheptel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruches', to='TP.cheptel')),
            ],
            options={
                'verbose_name': 'ruche',
                'verbose_name_plural': 'ruches',
            },
        ),
        migrations.CreateModel(
            name='Recolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ruche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoltes', to='TP.ruche')),
            ],
            options={
                'verbose_name': 'recolte',
                'verbose_name_plural': 'recoltes',
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('nature', models.CharField(choices=[('Suppression des cellules royales', 'Suppression des cellules royales'), ('Check de santé', 'Check de santé'), ('Récolte', 'Récolte'), ('Distribution de sirop', 'Distribution de sirop'), ('Pose de hausses', 'Pose de hausses'), ('Destruction', 'Destruction'), ("Multiplication artificielle de l'essaim", "Multiplication artificielle de l'essaim"), ('Traitement (apivar, acide oxalique, antifongique, ...)', 'Traitement (apivar, acide oxalique, antifongique, ...)')])),
                ('description', models.CharField(max_length=255)),
                ('ruche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='TP.ruche')),
            ],
            options={
                'verbose_name': 'intervention',
                'verbose_name_plural': 'interventions',
            },
        ),
        migrations.CreateModel(
            name='Contamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('maladie', models.CharField(choices=[('Varroa destructor', 'Varroa destructor'), ('Loque', 'Loque'), ('Nosémose', 'Nosémose'), ('Maladie noire', 'Maladie noire'), ('Acariose', 'Acariose'), ('Autres', 'Autres')], max_length=100)),
                ('traite', models.BooleanField()),
                ('ruche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contaminations', to='TP.ruche')),
            ],
            options={
                'verbose_name': 'contamination',
                'verbose_name_plural': 'contaminations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='tp_user_set', related_query_name='tp_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='tp_user_permission_set', related_query_name='tp_user_permission', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='apiculteur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TP.user'),
        ),
    ]
