# Generated by Django 5.0.1 on 2024-01-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contamination',
            name='date',
            field=models.DateField(),
        ),
    ]
