# Generated by Django 5.0.1 on 2024-01-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP', '0003_alter_intervention_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prenom',
        ),
        migrations.AddField(
            model_name='apiculteur',
            name='nom',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='apiculteur',
            name='prenom',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
