# Generated by Django 5.0.1 on 2024-01-13 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP', '0005_alter_cheptel_apiculteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheptel',
            name='apiculteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheptels', to='TP.apiculteur'),
        ),
        migrations.AlterField(
            model_name='ruche',
            name='statut',
            field=models.CharField(choices=[('Active', 'Active'), ('En attente', 'En attente'), ('Detruite', 'Détruite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ruche',
            name='type_abeille',
            field=models.CharField(choices=[('Apis mellifera', 'Apis mellifera (Abeille européenne)'), ('Apis cerana', 'Apis cerana (Abeille asiatique)'), ('Apis mellifera mellifera', 'Apis Mellifera Mellifera (Abeille noire)'), ('Apis mellifera ligustica', 'Apis Mellifera Ligustica (Abeille italienne)'), ('Apis mellifera caucasica', 'Apis mellifera caucasica (Abeille caucasienne)'), ('Apis mellifera carnica', 'Apis mellifera carnica (Abeille carolienne)'), ('Abeille buckfast', "L'abeille Buckfast"), ('Abeille charpentière xylocope', "L'abeille charpentière xylocope"), ('Autre', 'Autre')], max_length=29),
        ),
    ]
